- name: Fetch random salts for Wordpress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: wp_salt
  sudo: no
  tags: install
  run_once: true

- name: Create Wordpress database
  mysql_db: name={{ db_name }} state=present
  tags: install
  run_once: true

- name: Copy Wordpress config file
  template: src=wp-config.php.j2 dest={{ project_directory }}/wp-config.php
  tags: install
  run_once: true

- name: Install vendors, themes and plugin with composer
  composer: command=install working_dir={{ project_directory}}
  tags: install